---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - name: mysql-port
              containerPort: 3306

          resources:
            limits:
              ephemeral-storage: "1Gi"
              memory: 500Mi
              cpu: 200m
            requests:
              ephemeral-storage: "1Gi"
              memory: 500Mi
              cpu: 60m

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql-password
