kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.30.0.0/16
  apiServerAddress: 0.0.0.0
  apiServerPort: 1443
  disableDefaultCNI: true
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: /tmp/plugins/bin
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: /tmp/plugins/bin
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: /tmp/plugins/bin
      containerPath: /opt/cni/bin
