---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
    - port: 31201
      nodePort: 31101
      targetPort: wordpress-port
      protocol: TCP
  selector:
    app: wordpress
  type: LoadBalancer
