# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  
  config.vm.define :ubuntu do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.box_check_update = false

    # config.vm.network :private_network, :ip => '10.20.30.40'
    # config.vm.network :public_network, :ip => '10.20.30.41'
  
    # config.vm.synced_folder "./data", "/home/vagrant/data"

    config.vm.provider :libvirt do |domain|
      # domain.qemu_use_session = false
      domain.memory = 1024
      domain.cpus = 1
    end
  end
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = ''
    libvirt.driver = "kvm"

    # libvirt.connect_via_ssh = false

    # libvirt.host = "ubuntu"

    # libvirt.username = "root"
    # libvirt.password = "password"
  end
end
