apiVersion: v1
kind: Pod
metadata:
  name: helloworld-nginx-pod
  labels:
    app: helloworld-nginx
spec:
  containers:
    - name: k8s-demo
      image: wardviaene/k8s-demo
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: 200Mi
          cpu: 200m
        requests:
          memory: 160Mi
          cpu: 60m

    - name: nginx
      image: nginx:1.11
      ports:
        - name: nginx-port
          containerPort: 80
      resources:
        limits:
          memory: 200Mi
          cpu: 200m
        requests:
          memory: 160Mi
          cpu: 60m
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d

  volumes:
    - name: config-volume
      configMap:
        name: helloworld-nginx-config
        items:
          - key: reverseproxy.conf
            path: reverseproxy.conf # output file name
