# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(2) do |config|
  config.vm.hostname = "localhost"

  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.build_dir = "."
    docker.remains_running = true
    docker.has_ssh = true
  end
end